### ISSUE TITLE
Search by id in CQL TEXT

### ISSUE THREAD

**Issue by m-mohr** [microsoft/planetary-computer-apis#107]
**Describe the bug**
I request a specific Item via cql2-text encoding:
`https://planetarycomputer.microsoft.com/api/stac/v1/search?filter-lang=cql2-text&filter=id%20=%20%22MCD43A4.A2021189.h30v12.061.2021198054449%22`

Instead of a single result, I get an error: 

> "column \"MCD43A4.A2021189.h30v12.061.2021198054449\" does not exist"

Similarly, I'd assume it would work for items?

`https://planetarycomputer.microsoft.com/api/stac/v1/collections/modis-43A4-061/items?filter-lang=cql2-text&filter=id+%3D+%22MCD43A4.A2021189.h30v12.061.2021198054449%22`

I know there are other ways to filter by ID, but I'm looking at CQL right now in my client implementations.

**To reproduce**
See above.

**Expected behavior**
See above.

**Comment by mmcfarland** [comment]
@m-mohr this search works if you used an encoded single-quote instead of a double-quote for the value:

https://planetarycomputer.microsoft.com/api/stac/v1/search?filter-lang=cql2-text&filter=id=%27MCD43A4.A2021189.h30v12.061.2021198054449%27

This is the behavior of pgstac's implementation, which was informed by the examples on the [spec documentation](https://github.com/radiantearth/stac-api-spec/tree/master/fragments/filter#example-1-get-with-cql2-text).

**Comment by m-mohr** [comment]
Sorry, this is indeed my fault.
