### ISSUE TITLE
Errors during deployment process

### ISSUE THREAD

**Issue by maybe78** [microsoft/planetary-computer-apis#110]
We received several bugs during the deployment described in [README.md](https://github.com/microsoft/planetary-computer-apis#readme).

1. images ```stack``` and ```tiler``` in docker compose linked to ```docker.io hub instead``` instead ```mcr.microsoft.com``` 
2. the pccommon util id missing from api stac image and needs to be installed by pyhon
3. STAC api functions return "not found" instead json collections

**Comment by mmcfarland** [comment]
Hi @maybe78 - thanks for the issues. As noted in the readme, this repo is intended to serve as a reference implementation for an Azure-based deployment of the various STAC API and tiler tools used in the Planetary Computer. However, the readme instructions should be sufficient for getting a local development environment up and running.

> images stack and tiler in docker compose linked to docker.io hub instead instead mcr.microsoft.com

The docker-compose file references locally built and named images and isn't intended to pull from an external registry like mcr or docker hub. Did you run `./scripts/setup`, which would build those images locally?

> the pccommon util id missing from api stac image and needs to be installed by pyhon

The pccommon package is installed during the image build for both the `stac` and `tiler` services, in the respective Dockerfile. This should also be automatically handled via `setup` or `update` scripts.
https://github.com/microsoft/planetary-computer-apis/blob/836f304f34fb2a7e3fdcf756278ed4acc598dfb0/pcstac/Dockerfile#L12

> STAC api functions return "not found" instead json collections

Locally, running `setup` will create a pgstac instance and populate it with some test data, so that a `naip` collection should exist and be returned, e.g. at `http://localhost:8080/stac/collections/naip`. Any other data you will need to load yourself.

Hope this helps.

**Comment by maybe78** [comment]
Hi, @mmcfarland, thanks for prompt reply, it helped a lot. I thought that `stac` api is accessible at `localhost:8081` port as it mentioned in README.mr. And I'm receiving errors in browser console, because data catalogue is trying to reach api at `/api/stac/v1/collections`endpoint

**Comment by maybe78** [comment]
I finally finished installation by replacing pc-stac image with microsoft's one. Thank you for your help)

**Comment by mmcfarland** [comment]
Glad you were able to get the project running, I'll go ahead and close this issue.

FYI, I just cloned a clean checkout of this repo and ran `./scripts/setup.py`. After that completed, the services were up and running at :8080/stac and :8080/data
